version: "3.8"
services:
  backend:
    build:
      context: ./API
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    build:
      context: ./front/copmed-extension
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
